In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [12]:
from sklearn.datasets import load_digits
digits = load_digits()

In [14]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [28]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [30]:
le = LogisticRegression(max_iter=200)
le.fit(X_train, y_train)
le.score(X_test, y_test)

0.9416666666666667

In [32]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.975

In [34]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9638888888888889

In [40]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [48]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [50]:
def getscore(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [64]:
getscore(LogisticRegression(max_iter=150), X_train, X_test, y_train, y_test)

0.9416666666666667

In [70]:
from sklearn.model_selection import StratifiedKFold

In [94]:
fold = StratifiedKFold(n_splits=3)
selection_LR = []
selection_svm = []
selection_rf = []
for train_index,test_index in fold.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    selection_LR.append(getscore(LogisticRegression(max_iter=200), X_train, X_test, y_train, y_test))
    selection_svm.append(getscore(SVC(), X_train, X_test, y_train, y_test))
    selection_rf.append(getscore(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [95]:
selection_LR

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [98]:
selection_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [100]:
selection_rf

[0.9348914858096828, 0.9499165275459098, 0.9298831385642737]

In [102]:
from sklearn.model_selection import cross_val_score

In [110]:
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target, cv=5)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [112]:
cross_val_score(SVC(), digits.data, digits.target, cv=10)

array([0.94444444, 0.98888889, 0.92777778, 0.96666667, 0.98333333,
       0.98888889, 0.98888889, 0.99441341, 0.96089385, 0.95530726])

In [114]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=6)

array([0.93333333, 0.96333333, 0.96      , 0.97324415, 0.97324415,
       0.92307692])

In [118]:
import numpy as np

In [126]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(score1)  

0.9343420235878336

In [128]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(score2)  

0.9426846679081315

In [130]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=80), digits.data, digits.target, cv=10)
np.average(score3)  

0.9465704531346988

In [132]:
score4 = cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=10)
np.average(score4)  

0.9460180012414648

In [138]:
score5 = cross_val_score(RandomForestClassifier(n_estimators=120), digits.data, digits.target, cv=10)
np.average(score5)  

0.9493637492240843